### ISSUE TITLE
Rotating Dimmer value tag not available in certain Flow Card actions

### ISSUE THREAD

**Issue by luvis** [athombv/com.ikea.tradfri#56]
The #value tag on the round dimmer does not show up in the list of tags in the last step of a flow (homey 2.0) which makes the dimmer unusable.

**Comment by RobinBol** [comment]
Hi guys, I tried to reproduce the issue you describe, but it seems to work on my end (Homey firmware v2.0.0, Homey Smartphone App version 2.0.1.245). Maybe you are running an older software version, but it seems this issue has been resolved in the meanwhile (see .gif below). I will close this issue for now but please let me know when this remains an issue for you after you have updated to the software versions you can find above.

![screenrecording_01-14-2019 14-02-45](https://user-images.githubusercontent.com/5762579/51114831-c4139980-1806-11e9-8468-f7c779a2f62d.gif)

**Comment by luvis** [comment]
Hi, unfortunately your example seems to be the only thing that works, even
for me. Have you tried to dim a light with it? I won't be using it to send
push messages to my phone even if that works.. So the issue is still
currrnt in the latest update of both the app and homey. Would you check
please? It would be very helpful.

Thanks
David Campbell

**Comment by RobinBol** [comment]
Then I don't understand your issue, initially you mentioned that the value tag is not available, but now you confirm that the value tag actually is available?

If you wish to receive support, please contact support@athom.com. The GitHub issue tracker is only for development issues and is actually not actively used any more.

**Comment by luvis** [comment]
I'm sorry if my explanation was bad. I was also unaware that the github was
not meant for issues so I'm not expecting any help, however just for the
sake of being understood since the issue is still present, I also made a
video to show what I'm trying my best to explain.
Hope you can help or guide me. I have already sent a request to athom
support but since this seems to be a ikea-app issue I don't think it will
do much good. Please check the video.



[image: MP4 Video file]
20190114_20525.mp4
<https://drive.google.com/a/luvis.se/file/d/15KDLyx7l9myQTQUg_nXQMadNIBqsHjXI/view?usp=drivesdk>



Regards
David Campbell

**Comment by jampeef** [comment]
thats weird I too only see the rotating dimmer local value on the send push notification. when choosing dimto or set relative brightness (which i use it for) its not there so its definatly a bug.

**Comment by RobinBol** [comment]
@luvis thanks for the video, that helps a lot! I will discuss this with my colleagues, since it might be an issue in the smartphone app itself, I'll keep this issue open for now.

**Comment by luvis** [comment]
The latest update fixed the issue! Thank you very much 👍😁

**Comment by RobinBol** [comment]
Thanks for the feedback!
